#include <stdio.h>
#include <rpc/rpc.h>  /* always needed */
#include <string.h>
#include <stdlib.h>
#include <signal.h>
#include "processor.h"      /* msg.h will be generated by RPCGEN */
#define BUFFER_SIZE 1024
int line_num,sum_digitcounter = 0;
void sigintHandler(int sig_num)
{
    signal(SIGINT, sigintHandler);
    printf(" the number of lines received so far is %d and the total digit count is %d \n", line_num, sum_digitcounter);
    exit(EXIT_SUCCESS);
}
int *msgprocessor_1_svc(char **msg, struct svc_req *req)
{
	static int reply = 6233;
	int i, digit_counter;
	char buffer[BUFFER_SIZE];
	FILE *fpt;
	signal(SIGINT, sigintHandler);
	digit_counter = 0;
	strcpy(buffer,*msg);
	line_num++;
	for( i = 0; i< strlen(buffer); i++)
		if(buffer[i] >= 0x30 && buffer[i]<= 0x39)
			digit_counter++;
	sum_digitcounter += digit_counter;
	printf("the user input: %sthe number of digits: %d \n",buffer, digit_counter);
	fpt = fopen("secret.out","a");
	fprintf(fpt,"the user input: %sthe number of digits: %d \n",buffer, digit_counter);
	fclose(fpt);
	return &reply;
}

