#include <stdio.h>
#include <rpc/rpc.h>     /* always needed  */
#include "processor.h"         /* msg.h will be generated by RPCGEN */
#include <stdlib.h>
#define BUFFER_SIZE 1024
int main(int argc, char* argv[])
{
	CLIENT *cl;
	int *reply, i, str_len;
	char *server, *msg;
	char buffer[BUFFER_SIZE];
	char secret_key[] = "C00L";
	FILE *fpt;
	if (argc < 2) {
    	fprintf(stderr, "server ip address should be provided\n");
    	exit(EXIT_FAILURE);
	}
	server = argv[1];
	fpt = fopen("secret.out","w");
	fclose(fpt);
	/*
	* Create client "handle" used for calling MESSAGEPROG on the 
	* server designated on the command line. We tell the RPC package 
	* to use the "tcp" protocol when contacting the server.
	*/	
	cl = clnt_create(server, PROCESSORPROG, PROCESSORVERS, "tcp");
	if(cl == NULL){
		/* Couldn’t establish connection with server. * Print error message and die */

		exit(EXIT_FAILURE);
	}
    while(1){
		printf("Please enter the message: ");
		/* read from the user input */
        fgets(buffer, BUFFER_SIZE, stdin);
		str_len = strlen(buffer);
		/* check whether user enter an alpha numeric strings or not */
		for(i = 0; i< str_len - 1; i++)
		{
			if((buffer[i] >= 0x30 && buffer[i] <= 0x39) ||(buffer[i] >= 0x41 && buffer[i] <= 0x5A)||(buffer[i] >= 0x61 && buffer[i] <= 0x7A))
				continue;
			else
				break;
		}
		if(i == str_len - 1)
        	if(strstr(buffer, secret_key) != NULL){
				msg = buffer;
				reply = msgprocessor_1(&msg, cl);
				if (reply == NULL) {
				/* An error occurred while calling the server. * Print error message and die */

					exit(EXIT_FAILURE); 
				}
				if (*reply == 6233)
		   	 		printf("Message delivered\n");
			}
		}
    return EXIT_SUCCESS;
} 